### ISSUE TITLE
legacy session url not found

### ISSUE THREAD

**Issue by lborguetti** [Tigge/antfs-cli#170] opened 2018-04-12 22:59 UTC
I tried to upload activities but received this error: 

```
Downloading 1 file(s)                   
Downloading 2018-04-12_19-42-32_4_234.fit: [..............................] ETA:
2018-04-12 19:49:51,964 [INFO] Try to login on GarminConnect...                 
2018-04-12 19:49:55,091 [CRITICAL] Login Failure: 404 Client Error: Not Found for url: https://connect.garmin.com/legacy/session
```

The source code is updated, 

```
lucianofaustino  ~  projects  github  antfs-cli  git pull
Already up-to-date.
```

I think Garmin Connect disabled legacy url. Do you have the same error to? 

Thanks.

**Comment by rayoplateado** [comment] 2018-04-24 05:31
I have the same error. Can't upload my workouts

**Comment by Tigge** [comment] 2018-04-26 19:32
I'm not using it myself, and I'm not the author of that perticular script. Perhaps @codingtony or @La0 have an idea?

**Comment by mscansian** [comment] 2018-04-28 23:57
Might be related to [this](https://github.com/La0/garmin-uploader/issues/10)

**Comment by La0** [comment] 2018-05-03 12:29
@Tigge @mscansian Yes, this is the root cause: Garmin removed some API endpoints, so i had to update my uploader code.

`garmin-uploader` users should update their version installed to 1.0.4

**Comment by mscansian** [comment] 2018-08-25 01:46
We could probably close this one :)

**Closed** 2018-08-25 08:08 UTC
Labels: status:new, type:bug
